# Generated by Django 4.0.3 on 2022-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_trainapp_value_trainapp_epochs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='train_images/')),
            ],
        ),
    ]
