# Generated by Django 4.0.3 on 2022-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_trainimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamForNeural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
